### ISSUE TITLE
Uncaught TypeError: Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by alexmason81** [cakebake/markdown-themeable-pdf#11]
[Enter steps to reproduce below:]
1. Create or Open a Markdown File
2. Press Ctrl+Shift+E
3. Error message appears (see below)

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property 'html' of undefined

```
At /home/alex/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:417

TypeError: Cannot read property 'html' of undefined
  at /home/alex/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:417:42
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```
### Commands

```
     -1:24.6.0 core:select-all (atom-text-editor#markdown-themeable-pdf.customStylesPath.editor.mini.is-focused)
     -1:24.3.0 core:copy (atom-text-editor#markdown-themeable-pdf.customStylesPath.editor.mini.is-focused)
  2x -1:23.6.0 core:paste (atom-text-editor#markdown-themeable-pdf.customHeaderPath.editor.mini.is-focused)
     -0:00.8.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-format",
      "tidy-markdown",
      "markdown-pdf"
    ]
  },
  "markdown-themeable-pdf": {
    "customStylesPath": "/home/alex/.atom/markdown-themeable-pdf/",
    "customHeaderPath": "/home/alex/.atom/markdown-themeable-pdf/",
    "customFooterPath": "/home/alex/.atom/markdown-themeable-pdf/"
  }
}
```
### Installed Packages

``` coffee
# User
markdown-preview-opener, v0.1.1
markdown-preview-plus, v2.2.0
markdown-themeable-pdf, v0.10.0

# Dev
No dev packages
```

**Comment by alexmason81** [comment]
![screenshot from 2015-10-08 13 37 31](https://cloud.githubusercontent.com/assets/5288197/10374570/c98bf580-6dc1-11e5-9c8d-1b052cae26bd.png)

**Comment by alexmason81** [comment]
```
~$ ls -la /home/alex/.atom/markdown-themeable-pdf/
total 56
drwxrwxr-x 2 alex alex 4096 Sep 24 17:08 .
drwxrwxr-x 8 alex alex 4096 Sep  9 16:21 ..
-rw-rw-r-- 1 alex alex  798 Sep  9 16:21 footer.js
-rw-rw-r-- 1 alex alex  527 Sep  9 16:21 header.js
-rw-rw-r-- 1 alex alex  690 Sep 24 17:08 logo.png
-rw-rw-r-- 1 alex alex  417 Sep  9 16:21 styles.css

```

**Comment by alexmason81** [comment]
The only "customization" was to update the settings so the theme, header, and footer directories were defined (the default was empty and the suggested value was not a valid path). If I remove the values from those settings I can export to PDF, however this is puzzling as the suggested default directories do not even exist.

**Comment by alexmason81** [comment]
OK I found the solution. I didn't realize that you had to specify the file (rather than the directory) for the style, header, and footer. I specified the path to the exact files and it works now. Thank you and sorry for any trouble.

**Comment by cakebake** [comment]
No problem. But best issue report for now :)

**Comment by ryangyoung** [comment]
I've run into the exact same error, but specifying the absolute path didn't solve the problem for me. The steps to reproduce are identical to the OP. I can create a PDF without the custom footer just fine. I was also able to create a PDF with the default headers and footers. I've tried using paths relative to the default `.atom/markdown-themeable-pdf` and absolute paths using the project structure described in [issue 38](https://github.com/cakebake/markdown-themeable-pdf/issues/38), and got the same errors with those, too. 

## Stack Trace

`[Enter steps to reproduce below:]
1. Create .md file
2. Customized footer.js file
3. Restarted Atom
4. Right click, select `Markdown to PDF`

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.1
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'html' of undefined

```
At /Users/rgy/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:447

TypeError: Cannot read property 'html' of undefined
    at /Users/rgy/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:447:111
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### Commands

```
     -9:17.4.0 core:copy (atom-text-editor#markdown-themeable-pdf.customStylesPath.editor.mini.is-focused)
     -9:14.4.0 core:paste (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
 30x -9:11.5.0 core:move-right (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  4x -9:07.9.0 core:move-left (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
     -9:06.6.0 core:move-right (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  4x -9:05.8.0 core:backspace (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  3x -9:04.4.0 core:move-right (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
     -9:03.4.0 core:move-left (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  2x -9:02.8.0 core:move-right (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  2x -9:02.0 core:backspace (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  2x -9:00.2.0 core:move-left (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  4x -8:59.3.0 core:backspace (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
     -8:53.5.0 core:save (atom-text-editor#markdown-themeable-pdf.customFooterPath.editor.mini.is-focused)
  2x -8:43 markdown-themeable-pdf:export (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "markdown-themeable-pdf": {
    "customFooterPath": "/Users/rgy/Dropbox/doc/md-doc-project/footer.js",
    "customStylesPath": "/Users/rgy/Dropbox/doc/md-doc-project/document.css",
    "enableCustomHeader": false,
    "format": "Letter",
    "openPdfInAtomWorkspace": false,
    "preWrap": false
  }
}
```

### Installed Packages

``` coffee
# User
markdown-preview-plus, v2.4.0
markdown-themeable-pdf, v1.0.1

# Dev
No dev packages
```

**Comment by scorpiodawg** [comment]
I hit this error too. This happened when my footer (or header) customization script had an error (in my case it was a null reference, i.e. referencing an undefined variable). Fixing it made the problem go away.

**Comment by rgarrigue** [comment]
Hi

I hit the same issue, on a brand new installation both OS (Ubuntu 17.10 Budgie, & Atom 

```
➜  .atom apm -v
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.14
git 2.14.1
```

Thing is, ` ~/.atom/markdown-themeable-pdf is missing styles.css`

```
markdown-themeable-pdf:
total 16
drwxr-xr-x  2 remy remy 4096 janv. 22 15:59 .
drwx------ 10 remy remy 4096 janv. 22 16:05 ..
-rw-r--r--  1 remy remy  401 janv. 22 15:59 footer.js
-rw-r--r--  1 remy remy   82 janv. 22 15:59 header.js
```

Here are the errors

```
Start converting MyDoc.md
Stylesheet /home/remy/.atom/packages/markdown-themeable-pdf/css/document.css not found
Stylesheet /home/remy/.atom/markdown-themeable-pdf/styles.css not found
Stylesheet /home/remy/.atom/packages/markdown-themeable-pdf/node_modules/highlight.js/styles/github-gist.css not found
Could not process custom footer /home/remy/.atom/markdown-themeable-pdf/footer.js
```
