### ISSUE TITLE
Uncaught Error: Unknown encoding: gbk

### ISSUE THREAD

**Issue by duanbinbinbin** [cakebake/markdown-themeable-pdf#110]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 ia32
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught Error: Unknown encoding: gbk

```
At internal/fs.js:21

Error: Unknown encoding: gbk
    at assertEncoding (internal/fs.js:21:11)
    at getOptions (fs.js:80:5)
    at Object.fs.readFile (fs.js:338:13)
    at Object.fs.readFile (ELECTRON_ASAR.js:457:25)
    at Object.convertFile (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:344:12)
    at Object.exportEditor (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:538:25)
    at CommandRegistry.handleCommandEvent (D:/Atom/Atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (D:/Atom/Atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (D:/Atom/Atom/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (D:/Atom/Atom/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  3x -3:21.3.0 core:move-right (input.hidden-input)
     -3:19.3.0 core:backspace (input.hidden-input)
  3x -3:17.4.0 core:move-down (input.hidden-input)
     -3:11.5.0 autocomplete-plus:confirm (input.hidden-input)
 20x -3:10.4.0 core:backspace (input.hidden-input)
     -3:03.8.0 core:move-left (input.hidden-input)
     -3:03.5.0 editor:newline (input.hidden-input)
     -3:03.3.0 core:move-up (input.hidden-input)
  5x -3:01.0 core:backspace (input.hidden-input)
     -2:45.6.0 core:paste (input.hidden-input)
 16x -2:27.3.0 core:backspace (input.hidden-input)
     -0:48.2.0 editor:newline (input.hidden-input)
     -0:46.8.0 core:backspace (input.hidden-input)
     -0:45.2.0 editor:newline (input.hidden-input)
  2x -0:28.8.0 markdown-toc:toggle (div.line)
     -0:22.7.0 markdown-themeable-pdf:export (div.line.cursor-line)
```

### Non-Core Packages

```
language-markdown 0.26.0 
markdown-img-paste 0.3.11 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.3.3 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
markdown-toc 0.4.2 
simplified-chinese-menu 5.3.5 
```

**Comment by cakebake** [comment]
Please try UTF-8 encoding. Currently I am working on version 2. For version 1, there are no more updates. In v2 I made some tests with chinese encoding.
