### ISSUE TITLE
Uncaught Error: Cannot find module 'mdurl'

### ISSUE THREAD

**Issue by mirryi** [cakebake/markdown-themeable-pdf#114]
**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught Error: Cannot find module 'mdurl'

```
At module.js:545

Error: Cannot find module 'mdurl'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.31.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-themeable-pdf/node_modules/markdown-it/lib/common/utils.js:257:31)
    at /packages/markdown-themeable-pdf/node_modules/markdown-it/lib/common/utils.js:277:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-themeable-pdf/node_modules/markdown-it/lib/index.js:6:20)
    at /packages/markdown-themeable-pdf/node_modules/markdown-it/lib/index.js:579:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-themeable-pdf/node_modules/markdown-it/index.js:4:18)
    at /packages/markdown-themeable-pdf/node_modules/markdown-it/index.js:6:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.31.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.31.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
     -0:19.7.0 core:backspace (input.hidden-input)
     -0:13.4.0 markdown-themeable-pdf:export (span.syntax--markup.syntax--underline.syntax--link.syntax--gfm)
  2x -0:09.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-clock 0.1.16 
atom-html-preview 0.2.5 
atom-terminal 0.8.0 
autoclose-html 0.23.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
file-icons 2.1.25 
gitlab-integration 0.4.7 
language-batch 0.4.0 
markdown-pdf 2.2.0 
markdown-themeable-pdf 1.2.1 
open_in_cmd 0.6.1 
pdf-view 0.71.0 
pen-paper-coffee-syntax 0.17.0 
pigments 0.40.2 
script 3.18.1 
teletype 0.13.3 
tool-bar 1.1.10 
tool-bar-almighty 0.8.2 
```

**Comment by cakebake** [comment]
Because of the v1, it might help you just uninstall and reinstall the package once. Just try it out. It may be that used modules have not been downloaded correctly.

I am currently working [on the v2](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite). The v1 is no longer developed.
