### ISSUE TITLE
Active markdown-themeable-pdf error "can't find module lodash".

### ISSUE THREAD

**Issue by lisazeng99** [cakebake/markdown-themeable-pdf#123]
I installed the rewrite branch and when I enabled it, it shows error "can't find module lodash".

How can I solve this?

Below is copied 
[Enter steps to reproduce:]

1. install markdown-themeable-pdf from its atom web page.
2. it is installed and share error "can't find module lodash".
3. disable it and enable it again, the error still shows.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 2.0.0-dev

### Stack Trace

Failed to load the markdown-themeable-pdf package

At Cannot find module 'lodash'

```
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/markdown-themeable-pdf/lib/commands.js:9:15)
    at /packages/markdown-themeable-pdf/lib/commands.js:106:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/markdown-themeable-pdf/lib/index.js:4:31)
    at /packages/markdown-themeable-pdf/lib/index.js:37:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:666612)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3027983)
    at measure (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3014694)
    at Package.measure (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3013526)
    at Package.load (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3014267)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:381285)
    at config.transact (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:379708)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.8.0 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.15.10 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 2.0.0-dev 
markdown-toc 0.4.2 
markdown-writer 2.11.5 
vim-mode-plus 1.36.0 
```

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
