### ISSUE TITLE
Uncaught TypeError: Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by itlinux** [cakebake/markdown-themeable-pdf#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.10.1
### Stack Trace

Uncaught TypeError: Parameter 'url' must be a string, not undefined

```
At /Users/remo/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:335

TypeError: Parameter 'url' must be a string, not undefined
  at Url.parse (url.js:90:11)
  at Object.urlParse [as parse] (url.js:84:5)
  at Object.module.exports.markdownThemeablePdf.resolveImgSrc (/Users/remo/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:524:17)
  at Object.<anonymous> (/Users/remo/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:298:63)
  at [object Object].exports.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/api/traversing.js:267:24)
  at Object.md.renderer.rules.html_block (/Users/remo/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:297:26)
  at Renderer.render (/Users/remo/.atom/packages/markdown-preview-plus/node_modules/markdown-it/lib/renderer.js:292:38)
  at MarkdownIt.render (/Users/remo/.atom/packages/markdown-preview-plus/node_modules/markdown-it/lib/index.js:513:24)
  at /Users/remo/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:333:31
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -9:35.8.0 application:minimize (div.settings-view.pane-item)
     -9:22.5.0 markdown-katex-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -8:46.3.0 markdown-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -8:19.6.0 markdown-preview-plus:toggle-render-latex (div.markdown-preview.native-key-bindings)
     -8:09.4.0 markdown-pdf:convert (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -8:02.9.0 markdown-preview-plus:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:16.9.0 settings-view:install-packages-and-themes (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:56.2.0 markdown-themeable-pdf:export (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-themeable-pdf": {}
}
```
### Installed Packages

``` coffee
# User
add-line-break, v0.2.0
ascii-codes, v0.3.3
asciidoc-preview, v0.6.0
atom-markdown-katex, v0.3.7
color-picker, v2.0.11
language-asciidoc, v0.11.1
markdown-deluxe, v1.0.0
markdown-pdf, v1.3.9
markdown-preview-plus, v2.2.2
markdown-preview-plus-opener, v0.2.0
markdown-themeable-pdf, v0.10.1
vim-mode, v0.58.0
vim-mode-visual-block, v0.2.13
wrap, v0.1.0

# Dev
No dev packages
```

**Comment by cakebake** [comment]
Could you enter steps to reproduce? Any further information??
