### ISSUE TITLE
Uncaught Error: 2015-10-20T13:40:17 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed ...

### ISSUE THREAD

**Issue by dikamilo** [cakebake/markdown-themeable-pdf#15]
1. Set export to pdf
2. Open markdown file
3. run export command form commands palete

Image and html export works fine.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.10.1
### Stack Trace

Uncaught Error: 2015-10-20T13:40:17 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (Serwer RPC jest niedost?pny.)
2015-10-20T13:40:17 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (Serwer RPC jest niedost?pny.)

```
At C:\Users\Kamil\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:458

Error: 2015-10-20T13:40:17 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (Serwer RPC jest niedost?pny.)
2015-10-20T13:40:17 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (Serwer RPC jest niedost?pny.)

  at ChildProcess.<anonymous> (C:\Users\Kamil\.atom\packages\markdown-themeable-pdf\node_modules\html-pdf\lib\pdf.js:123:17)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -3:05.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:01.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:01.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:55.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -2:52.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:51.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:44.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:44.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:40.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:39.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -2:37.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:36.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:36 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:36 markdown-themeable-pdf:export (atom-text-editor.editor)
     -2:21.2.0 settings-view:open (atom-text-editor.editor)
  4x -2:14.2.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "release-notes",
      "autoclose-html",
      "Zen",
      "build-tools",
      "emmet"
    ]
  },
  "markdown-themeable-pdf": {
    "openPdfInAtomWorkspace": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
atom-django, v0.3.0
atom-html-preview, v0.1.11
atom-minify, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.6.2
bookmarks, v0.38.0
coffee-compile, v0.19.1
color-picker, v2.0.13
deprecation-cop, v0.54.0
file-type-icons, v0.7.3
flex-tool-bar, v0.5.0
imdone-atom, v1.1.45
incompatible-packages, v0.25.0
indent-guide-improved, v1.4.3
keyboard-localization, v1.4.9
language-aspx, v0.4.0
language-batch, v0.3.3
language-gfm, v0.81.0
language-go, v0.39.0
language-mustache, v0.13.0
language-objective-c, v0.15.0
language-powershell, v2.1.0
language-ruby, v0.60.0
language-ruby-on-rails, v0.23.0
language-yaml, v0.24.0
linter, v1.8.1
linter-bootlint, v0.0.6
linter-coffeescript, v1.0.0
linter-csslint, v1.1.0
linter-jshint, v1.2.1
linter-pep8, v1.0.1
markdown-themeable-pdf, v0.10.1
metrics, v0.52.0
minimap, v4.13.4
minimap-linter, v1.0.0
monokai-syntax-for-one-dark, v0.2.2
pigments, v0.15.0
project-manager, v2.6.1
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1
tool-bar, v0.1.9
webbox-color, v0.5.8
welcome, v0.30.0

# Dev
No dev packages
```

**Comment by cakebake** [comment]
Ok, I think this is an phantomjs issue, which I could not solve. Do you have still issues, or just once...?

**Comment by cakebake** [comment]
If the error is still up to date, write in this Ticket

**Comment by dikamilo** [comment]
This was issue with Windows print service - if print service is disabled, phantomjs will fail.

**Comment by cakebake** [comment]
Thank´s for response :)
