### ISSUE TITLE
Uncaught TypeError: htmlToPdf.create(...).toStream is not a function

### ISSUE THREAD

**Issue by ivomarsan** [cakebake/markdown-themeable-pdf#18]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.10.1
### Stack Trace

Uncaught TypeError: htmlToPdf.create(...).toStream is not a function

```
At /home/ivomarsan/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:455

TypeError: htmlToPdf.create(...).toStream is not a function
  at /home/ivomarsan/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:455:20
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```
### Commands

```
  2x -7:02.2.0 core:save (atom-text-editor.editor.is-focused)
     -7:00.6.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
  8x -6:59.5.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
  3x -6:54.6.0 core:select-up (atom-text-editor.editor.is-focused)
     -6:54 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -6:53.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:53.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -6:52.5.0 core:close (atom-text-editor.editor.is-focused)
     -6:26.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -6:17.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:13.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:23.3.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
  2x -2:21.3.0 markdown-preview-plus:toggle-render-latex (atom-text-editor.editor.is-focused)
  2x -2:18.1.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
     -0:24.7.0 pane:show-previous-item (button.btn.btn-default.icon.icon-link)
  2x -0:24.1.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-themeable-pdf": {}
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.12
autocomplete-emojis, v2.2.2
file-icons, v1.6.11
linter, v1.10.0
markdown-preview-plus, v2.2.2
markdown-themeable-pdf, v0.10.1
mathjax-wrapper, v0.1.0
minimap, v4.16.0
pigments, v0.18.1
save-session, v0.15.7
selector-to-tag, v0.4.1
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

I need help

**Comment by cakebake** [comment]
Please describe in detail your problem. Always experience the same issue, or only one time? Have you tried to save in different places (writable), etc.? Plugin reinstalled, etc.?

**Comment by ivomarsan** [comment]
It always happens when I export the PDF. always always

**Comment by dpwrussell** [comment]
This happened to me because I had markdown-pdf installed. Once I installed it and restarted Atom, the error went away.

**Comment by ivomarsan** [comment]
LoL, thanks @dpwrussell It's working!

**Comment by cakebake** [comment]
I think this is a package conflict because both plugins use `phantomjs` to render the pdf :/ However, I still could not understand the conflict.....

**Comment by mondwan** [comment]
I got this error too.

Although reopening atom will solve this problem, it always re-happen if I change setting of this module

# Packages

```
├── atom-material-syntax@0.4.3
├── atom-material-ui@1.2.0
├── autocomplete-python@1.6.1
├── git-plus@5.13.0
├── language-gherkin@1.0.3
├── language-lua@0.9.4
├── linter@1.11.3
├── linter-eslint@7.0.0
├── linter-lua@1.0.1
├── markdown-pdf@1.3.9
├── markdown-themeable-pdf@0.10.2
├── pdf-view@0.39.0
├── python-autopep8@0.1.3
├── react@0.14.1
└── tomorrow-night-eighties-syntax@0.11.0
```

**Comment by cakebake** [comment]
@mondwan pls see dpwrussell´s comment to this issue
