### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stream' of undefined

### ISSUE THREAD

**Issue by Professidero** [cakebake/markdown-themeable-pdf#2]
[Enter steps to reproduce below:]
1. Use the package

**Atom Version**: 1.0.7
**System**:  Windows Version 7 Home Premium
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'stream' of undefined

```
At C:\Users\Florian\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:85

TypeError: Cannot read property 'stream' of undefined
    at C:\Users\Florian\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:85:24
    at C:\Users\Florian\.atom\packages\markdown-themeable-pdf\node_modules\phantom-html-to-pdf\lib\phantomWebServerStrategy.js:38:24
    at C:\Users\Florian\.atom\packages\markdown-themeable-pdf\node_modules\phantom-html-to-pdf\node_modules\phantom-workers\lib\phantomManager.js:90:13
    at C:\Users\Florian\.atom\packages\markdown-themeable-pdf\node_modules\phantom-html-to-pdf\node_modules\phantom-workers\lib\phantomWorker.js:92:20
    at Socket.<anonymous> (C:\Users\Florian\.atom\packages\markdown-themeable-pdf\node_modules\phantom-html-to-pdf\node_modules\phantom-workers\lib\checkPortStatus.js:45:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at TCP.close (net.js:464:12)
```
### Commands

```
  3x -3:07.5.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -2:58.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap-git-diff",
      "markdown-table-formatter",
      "autocomplete-ruby",
      "atomatigit",
      "git-go",
      "language-diff"
    ],
    "projectHome": "E:\\Documents personnels\\Informatique\\"
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.11
autohide-tree-view, v0.24.0
color-picker, v2.0.11
highlight-selected, v0.10.1
linter, v1.4.3
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-less, v2.0.3
linter-ruby, v1.0.1
markdown-mindmap, v0.2.2
markdown-themeable-pdf, v0.2.0
minimap, v4.12.3
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.3.0
minimap-linter, v1.0.0
pdf-view, v0.23.0
ruby-block, v0.3.5
seti-icons, v0.4.2
Sublime-Style-Column-Selection, v1.3.0
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

I got this problem even after rebooting my PC since the last update, but it doesn't appear on my Debian virtual machine, the package is working fine and as expected on the VM.

**Comment by cakebake** [comment]
Thank´s for your report.

I could not reproduce the error for my setup. However, maybe it´s obsolete, since I switched to another phantomjs wrapper in v0.3.0

Possibly, it has to do with a local firewall or write privileges... If you still have the same problems, just write again about this Issue.
