### ISSUE TITLE
Uncaught Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.

### ISSUE THREAD

**Issue by BodhiHu** [cakebake/markdown-themeable-pdf#40]
Hi when trying to generate pdf from markdown, this error often occurs: 

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.10.2
### Stack Trace

Uncaught Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.

```
At /Users/chrishu/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:470

Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.
    at ChildProcess.<anonymous> (/Users/chrishu/.atom/packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:111:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -1:39.1.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:36.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:36.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:31.2.0 markdown-preview:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:27.7.0 core:close (div.markdown-preview.native-key-bindings)
     -1:25.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -1:23.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:22.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:22.6.0 markdown-themeable-pdf:export (atom-text-editor.editor.vim-mode.normal-mode)
     -0:42.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:41 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:41 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:36.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:34.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:32.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.4.0 markdown-themeable-pdf:export (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "markdown-themeable-pdf": {
    "enableCustomFooter": false,
    "enableCustomHeader": false
  }
}
```

Best wishes : )

**Comment by cakebake** [comment]
Unfortunately I have no mac. :/ 

I think that this is an issue with PhantomJS. I hope that you can still work with the package.

**Comment by dimasmjunior** [comment]
I'm having the same issue in Fedora 23, after updating to Atom 1.8.0.

**Comment by isaactopo** [comment]
Same here with Atom 1.16

**Comment by MarcuSacramento** [comment]
Same here with Atom 1.18.0 and Windows 7

**Comment by ibrychgo** [comment]
Did you ever resolve this? Having a similar issue.

**Comment by purplediane** [comment]
I worked around it by closing all other programs. I have an old Mac, so everything is slow.

**Comment by cakebake** [comment]
Hello!

I take this as an incentive in version 2 of markdown-themeable-pdf to be able to edit the timeout in the package settings #121.

> Did you ever resolve this? Having a similar issue.

Otherwise, timeouts always have something to do with missing resources or too big documents.
