### ISSUE TITLE
Fontconfig error: junk after document element

### ISSUE THREAD

**Issue by andrade** [cakebake/markdown-themeable-pdf#46]
When I right-click and select "Markdown to PDF" I get the following error:

```
Uncaught Error: Fontconfig error:
"/home/daniel/.config/fontconfig/fonts.conf", line 7: junk after document element
```

Stack trace:

```
/home/daniel/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:472

Error: Fontconfig error: "/home/daniel/.config/fontconfig/fonts.conf", line 7: junk after document element
    at ChildProcess.<anonymous> (/home/daniel/.atom/packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:111:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Using Ubuntu 14.04 and Atom 1.7.3. I've checked for package updates and it says everything is up to date.

**Comment by cakebake** [comment]
This is OS related. Please check your font configuration on ubuntu.
