### ISSUE TITLE
failure to export pdf

### ISSUE THREAD

**Issue by silverlining21** [cakebake/markdown-themeable-pdf#56]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v1.2.0
### Stack Trace

Uncaught AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

```
At assert.js:89

AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at new PDF (C:\Users\HuangDian\.atom\packages\markdown-themeable-pdf\node_modules\html-pdf\lib\pdf.js:38:3)
    at Object.createPdf [as create] (C:\Users\HuangDian\.atom\packages\markdown-themeable-pdf\node_modules\html-pdf\lib\index.js:10:14)
    at C:\Users\HuangDian\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:483:27
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
     -0:05.9.0 markdown-themeable-pdf:export (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-pdf"
    ]
  },
  "markdown-themeable-pdf": {}
}
```
### Installed Packages

``` coffee
# User
markdown-pdf, v1.5.0 (inactive)
markdown-themeable-pdf, v1.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by cakebake** [comment]
This issue occurs from time to time, but was always OS dependent. Here I can not do much more than to recommend you perform a clean installation and read the closed Issues.

See #17

**Comment by grantrostig** [comment]
NOTE: the default usage of html-pdf may not work since the NAME CHANGE of phantomjs to >>>phantomjs-prebuilt<<<.

evidence is here:

npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

The options on the last line below,  probably need to be set as follows in your code(doing this did not fix it for me, but at least I got past that error message):

```
            htmlToPdf.create(dom, {
                format: absolute ? undefined : atom.config.get('markdown-themeable-pdf.format'),
                width: absolute ? width : undefined,
                height: absolute ? height : undefined,
                orientation: atom.config.get('markdown-themeable-pdf.orientation'),
                border: atom.config.get('markdown-themeable-pdf.pageBorder'),
                type: jobInfo.exportType,
                quality: atom.config.get('markdown-themeable-pdf.imageQuality'),
                header: customHeader,
                footer: customFooter,
                phantomPath: "./node_modules/phantomjs-prebuilt/bin/phantomjs"
```
