### ISSUE TITLE
Uncaught Error: Fatal Windows exception, code 0xc0000005. PhantomJS has crashed. 

### ISSUE THREAD

**Issue by Sugaryou** [cakebake/markdown-themeable-pdf#59]
I use it and then it failed.

C:\Users\Sugaryou.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:496
Hide Stack Trace
Error: Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.
    at ChildProcess.<anonymous> (C:\Users\Sugaryou.atom\packages\markdown-themeable-pdf\node_modules\html-pdf\lib\pdf.js:121:17)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by cakebake** [comment]
A phantomJS problem. A reboot of Atom should be enough
