### ISSUE TITLE
Cannot find module 'ncp'

### ISSUE THREAD

**Issue by agodlydeciple** [cakebake/markdown-themeable-pdf#6]
After I install your module, atom throws an error claiming it cannot find the module 'ncp'.  I had to install your module by downloading the git repo and manually placing it in my packages folder as I am behind a firewall at work and cannot install anything directly through atom.
### Here is How I produced the error:
1. Manually place markdown-themable-pdf-master folder in packages folder of atom
2. Open Atom
3. Error thrown

**Atom Version**: 1.0.13
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.9.0
### Stack Trace

Failed to activate the markdown-themeable-pdf package

```
At Cannot find module 'ncp'

Error: Cannot find module 'ncp'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\rr146019\AppData\Local\atom\app-1.0.13\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.module.exports.markdownThemeablePdf.activate (C:\Users\rr146019\.atom\packages\markdown-themeable-pdf-master\lib\markdown-themeable-pdf.js:184:19)
    at Package.module.exports.Package.activateNow (C:\Users\rr146019\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:245:19)
    at C:\Users\rr146019\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:226:30
    at Package.module.exports.Package.measure (C:\Users\rr146019\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:169:15)
    at Package.module.exports.Package.activate (C:\Users\rr146019\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:218:14)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "followSymlinks": true
  }
}
```
#### User
- language-csharp
- language-vb
- markdown-pdf
- markdown-themable-pdf
- node-html-pdf
#### Dev

No dev packages

**Comment by cakebake** [comment]
Hmm... if you place it manually in to the packages dir, you must load also the dependencies manually. You have two ways:
1. Open markdown-themeable-pdf folder with atom and run "update package dependencies" (or something similar) or
2. Download dependencies manually from github. You can find them defined in package.json in the dependencies section 

```
"dependencies": {
    "ncp": "*",
    "markdown-it": "*",
    "markdown-it-checkbox": "*",
    "markdown-it-smartarrows": "*",
    "html-pdf": "*",
    "highlight.js": "*",
    "cheerio": "*"
  }
```

Hope this helps! I could not test it at the moment because I am not at home ;)

Edit: I could send you a complete Zip archive with all downloaded dependencies, if you like. I think this is the easiest option you could go ^^

**Comment by cakebake** [comment]
Since there is no failure of the package, I close the ticket now. ;) If you need assistance in the use, feel free to write here again and come back to my suggestion.
