### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by MikkCZ** [cakebake/markdown-themeable-pdf#61]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v1.2.0
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /home/travis/build/atom/atom/out/app/src/decoration-manager.coffee:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/usr/share/atom/resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/share/atom/resources/app.asar/src/text-editor.js:1657:37)
    at /home/michal/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:227:32
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:949:18
    at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:987:9)
    at TextBuffer.module.exports.TextBuffer.scan (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:945:19)
    at TextEditor.module.exports.TextEditor.scan (/usr/share/atom/resources/app.asar/src/text-editor.js:2598:26)
    at /home/michal/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:226:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427:25
```
### Commands

```
  7x -0:26.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:17.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:17.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:14.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:14.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:14.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:09.2.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```
### Installed Packages

``` coffee
# User
markdown-themeable-pdf, v1.2.0 (active)
pdf-view, v0.50.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ChrisDowning** [comment]
Hope commenting here is the right thing to do... was directed to this issue from Atom editor when using markdown-themeable-pdf.

Issue first occured for me when, for example, removing "---" (horizontal rule) from the editor pane and pasting in the HTML to get a page break instead. On further investigation, **any** edit to the file seems to trigger the warning.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: "Fedora release
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v1.2.0


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/share/atom/resources/app.asar/src/decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/usr/share/atom/resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/share/atom/resources/app.asar/src/text-editor.js:1662:37)
    at /home/chris/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:227:32
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:949:18
    at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:987:9)
    at TextBuffer.module.exports.TextBuffer.scan (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:945:19)
    at TextEditor.module.exports.TextEditor.scan (/usr/share/atom/resources/app.asar/src/text-editor.js:2602:26)
    at /home/chris/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:226:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427:25
```

### Commands

```
     -3:53.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -3:51.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:48.8.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -3:32.4.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
  2x -1:24.3.0 core:copy (atom-text-editor.editor.is-focused)
  3x -1:03.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:01.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:43 core:backspace (atom-text-editor.editor.is-focused)
     -0:41.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:24 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -0:00.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-pdf"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-pdf, v1.5.0 (inactive)
markdown-themeable-pdf, v1.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (active)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ovizii** [comment]
I just started getting this same error over and over again, almost with every edit which makes atom unusable and I really need markdown-themeable-pdf :-( 

## Versions

* **Atom:**       1.16.0
* **Atom-Shell:** 
* **OS:**         Windows 7 Pro
* **Misc**
    * apm  1.16.1
    * npm  3.10.5
    * node 6.9.5 x64
    * python 
    * git 
    * visual studio 


**Uncaught Error: Cannot decorate a destroyed marker**
C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\src\decoration-manager.js:204

**Stack Trace**

```
Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\src\decoration-manager.js:194:17)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\src\text-editor.js:1732:37)
    at C:\Users\owpa\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:227:32
    at ForwardsSingleLine.iterate (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\match-iterator.js:67:11)
    at TextBuffer.module.exports.TextBuffer.scanInRange (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:939:23)
    at TextBuffer.module.exports.TextBuffer.scan (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:907:19)
    at TextEditor.module.exports.TextEditor.scan (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\src\text-editor.js:2673:26)
    at C:\Users\owpa\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:226:28
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
    at C:\Users\owpa\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1392:25
The error was thrown from the markdown-themeable-pdf package. This issue has already been reported.
```
