### ISSUE TITLE
Failed to load the markdown-themeable-pdf package

### ISSUE THREAD

**Issue by iwangdonghui** [cakebake/markdown-themeable-pdf#67]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v1.2.0

### Stack Trace

Failed to load the markdown-themeable-pdf package

```
At ENOENT: no such file or directory, scandir '/Users/wangdonghui/.atom/packages/markdown-themeable-pdf-master/node_modules/highlight.js/styles'

Error: ENOENT: no such file or directory, scandir '/Users/wangdonghui/.atom/packages/markdown-themeable-pdf-master/node_modules/highlight.js/styles'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at /Users/wangdonghui/.atom/packages/markdown-themeable-pdf-master/lib/markdown-themeable-pdf.js:129:32
    at Object.<anonymous> (/Users/wangdonghui/.atom/packages/markdown-themeable-pdf-master/lib/markdown-themeable-pdf.js:136:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:747:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:118:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:772:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.22 (inactive)
linter, v1.11.18 (inactive)
linter-markdown, v3.0.2 (inactive)
markdown-preview-plus, v2.4.0 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
markdown-themeable-pdf, v1.2.0 (inactive)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.6.2 (inactive)
tidy-markdown, v3.0.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by cakebake** [comment]
Duplicate to #74

**Comment by lisazeng99** [comment]
I installed the rewrite branch and when I enabled it, it shows error "can't find module lodash".

How can I solve this?

Below is copied 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 2.0.0-dev


### Stack Trace

Failed to load the markdown-themeable-pdf package

At Cannot find module 'lodash'

```
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/markdown-themeable-pdf/lib/commands.js:9:15)
    at /packages/markdown-themeable-pdf/lib/commands.js:106:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/markdown-themeable-pdf/lib/index.js:4:31)
    at /packages/markdown-themeable-pdf/lib/index.js:37:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:666612)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3027983)
    at measure (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3014694)
    at Package.measure (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3013526)
    at Package.load (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3014267)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:381285)
    at config.transact (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:379708)
```

### Commands

```
```

### Non-Core Packages

```
Hydrogen 2.8.0 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.15.10 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 2.0.0-dev 
markdown-toc 0.4.2 
markdown-writer 2.11.5 
vim-mode-plus 1.36.0 
```
