### ISSUE TITLE
Uncaught Error: Unknown encoding: windows1252

### ISSUE THREAD

**Issue by FluidCoding** [cakebake/markdown-themeable-pdf#84]
[Enter steps to reproduce:]

1. Use Windows-1252 Encoding
2. Run Markdown PDF

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.0

### Stack Trace

Uncaught Error: Unknown encoding: windows1252

```
At fs.js:129

Error: Unknown encoding: windows1252
    at assertEncoding (fs.js:129:11)
    at Object.fs.readFile (fs.js:283:3)
    at Object.fs.readFile (ELECTRON_ASAR.js:451:25)
    at Object.convertFile (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:344:12)
    at Object.exportEditor (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:538:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:19.9.0 markdown-themeable-pdf:export (div.line)
```

### Non-Core Packages

```
improved-asp-html 1.13.1 
markdown-preview-plus 2.4.10 
markdown-table-editor 0.6.0 
markdown-table-formatter 2.9.0 
markdown-themeable-pdf 1.2.0 
split-diff 1.4.3 
tidy-markdown 3.0.1 
```

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
