### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by ovizii** [cakebake/markdown-themeable-pdf#86]
[Enter steps to reproduce:]

1. move cursor wgile editing, simply saving, anything actually.

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: WS232
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\owpa\AppData\Local\atom\app-1.19.2\resources\app\src\decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (~/AppData/Local/atom/app-1.19.2/resources/app/src/decoration-manager.js:183:27)
    at TextEditor.module.exports.TextEditor.decorateMarker (~/AppData/Local/atom/app-1.19.2/resources/app/src/text-editor.js:1811:43)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:227:32
    at ForwardsSingleLine.iterate (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/text-buffer/lib/match-iterator.js:94:17)
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1033:29)
    at TextBuffer.module.exports.TextBuffer.scan (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:986:25)
    at TextEditor.module.exports.TextEditor.scan (~/AppData/Local/atom/app-1.19.2/resources/app/src/text-editor.js:2733:32)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:226:28
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1571:26)
    at later (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
  2x -7:25.2.0 core:delete (input.hidden-input)
     -7:24.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
 16x -7:16.5.0 core:paste (input.hidden-input)
     -3:19.3.0 core:save (input.hidden-input)
  4x -2:40.7.0 core:paste (input.hidden-input)
  4x -0:57.1.0 editor:move-to-beginning-of-word (input.hidden-input)
  3x -0:52.5.0 core:move-left (input.hidden-input)
     -0:51.8.0 editor:move-to-first-character-of-line (input.hidden-input)
  4x -0:51.5.0 core:move-right (input.hidden-input)
  2x -0:46.8.0 core:select-left (input.hidden-input)
     -0:45.9.0 core:copy (input.hidden-input)
  8x -0:45.5.0 editor:move-to-end-of-word (input.hidden-input)
     -0:42.9.0 core:paste (input.hidden-input)
     -0:42.2.0 core:move-right (input.hidden-input)
     -0:40 core:save (input.hidden-input)
  2x -0:39.1.0 markdown-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
bug-report 0.7.1 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
```

**Comment by cakebake** [comment]
Seems like a atom core bug. Sry
